# Test packages

## Numpy

In [1]:
import numpy as np

print(np.zeros([3, 4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## PyTorch

In [1]:
import torch

random_points = torch.rand(2, 9)
print(random_points)

ModuleNotFoundError: No module named 'torch'

## Matplotlib

### Display points

In [3]:
import matplotlib.pyplot as plt

plt.scatter(random_points[0], random_points[1])

NameError: name 'random_points' is not defined

## Seaborn

In [ ]:
import seaborn as sns; sns.set(); sns.set_palette('bright')

In [ ]:
plt.scatter(random_points[0], random_points[1])

### Display randomly generated image

In [ ]:
random_image = torch.rand(64, 64, 3)

plt.imshow(random_image)

### Display image from file

In [ ]:
import matplotlib.image as mpimg

img = mpimg.imread('logo.png')
plt.imshow(img)

## Pillow

### Display image from file

In [ ]:
from PIL import Image

img_pil = Image.open("logo.png")
img_pil

### Open image in new window

In [ ]:
img_pil.show()

## Sklearn

In [ ]:
from sklearn import datasets

iris = datasets.load_iris()
iris_x = np.array(iris.data[:, :2])  # we only take the first two features.
iris_t = np.array(iris.target)

def plot_iris(legend=True, classes=iris_t, target=plt):
    scatter = target.scatter(iris_x[:, 0], iris_x[:, 1], c=classes, alpha=0.7, cmap='rainbow', edgecolor='none')
    if legend:
        legend = target.legend(*scatter.legend_elements(), loc="upper left", title="Classes")
        return (scatter, legend)
    return (scatter, )

plot_iris()

## Scipy

In [ ]:
from scipy.stats import multivariate_normal

def generate_multi_gaussian_data(size, mean, covariance):
    return np.array(multivariate_normal(mean=mean, cov=covariance).rvs(size=size, random_state=26))

def display_gaussian_contour(data, mean, covariance, cmap='summer'):

    lx = min(data[:, 0])
    rx = max(data[:, 0])
    by = min(data[:, 1])
    uy = max(data[:, 1])

    x, y = np.mgrid[lx:rx:.01, by:uy:.01]
    pos = np.dstack((x, y))
    plt.contour(x, y, multivariate_normal(mean, covariance).pdf(pos), cmap=cmap)

target_mean = [1.7, -4]
target_cov = [[1, 0.1], [0.1, 1]]
multi_gaussian_data = generate_multi_gaussian_data(50, target_mean, target_cov)

plt.plot(multi_gaussian_data[:, 0], multi_gaussian_data[:, 1], '.')
display_gaussian_contour(multi_gaussian_data, target_mean, target_cov)